# Generated by Django 5.0 on 2024-01-29 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id_pegawai', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubVariabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=10)),
                ('faktor', models.CharField(choices=[('CORE', 'Core'), ('SECONDARY', 'Secondary')], default='CORE', max_length=10)),
                ('standar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Variabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('faktor', models.CharField(choices=[('CORE', 'Core'), ('SECONDARY', 'Secondary')], default='CORE', max_length=10)),
                ('persentase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.IntegerField()),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.pegawai')),
                ('sub_variabel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.subvariabel')),
            ],
        ),
    ]
