# Generated by Django 3.2.6 on 2024-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='id_pegawai',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
