# Generated by Django 4.1 on 2024-02-15 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_alter_pegawai_id_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvariabel',
            name='variabel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='example.variabel'),
        ),
    ]
